// Import from the new puzzle loader service
export {
  N_SQUARED_PLUS_N_CUBED_THETA_N_CUBED,
  LOG_N_IS_O_N,
  N_LOG_N_IS_O_N_SQUARED,
  TWO_TO_N_IS_NOT_O_N_CUBED,
  SUM_OF_FIRST_N_INTEGERS,
  SUM_OF_POWERS_OF_TWO,
  DIVISIBILITY_BY_THREE,
  DISTRIBUTIVE_LAW_SETS,
  DE_MORGAN_LAW,
  FIBONACCI_RECURSION,
  TOWERS_OF_HANOI,
  ALL_PUZZLES,
  PUZZLES_BY_CATEGORY,
  CATEGORIES,
  PuzzleLoader
} from '../services/puzzleLoader';